Base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]  + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import home, galeria, contacto, galeria2, agregar_producto, agregar_trabajador, \
    listar_productos, modificar_producto, eliminar_producto, registro, eliminar_producto_c ,carrito, \
    restar_producto, limpiar_carrito, agregara , webpay , usuario

urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('trabajadores/', galeria, name="galeria"),
    path('galeria/', galeria2, name="galeria2"),
    path('agregar_producto/', agregar_producto, name="agregar_producto"),
    path('agregar_trabajador/', agregar_trabajador, name="agregar_trabajador"),
    path('listar_productos/', listar_productos, name="listar_productos"),
    path('modificar_producto/<int:id>/', modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<int:id>/', eliminar_producto, name="eliminar_producto"),
    path('registro/', registro, name="registro"),
    path('usuario/', usuario, name="usuario"),
    path('webpay/', webpay, name="webpay"),
    path('carrito/', carrito, name="carrito"),
    path('agregar/<int:producto_id>/', agregara, name="Add"),
    path('eliminar/<int:producto_id>/', eliminar_producto_c, name="Del"),
    path('restar/<int:producto_id>/', restar_producto, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

app/models.py
from django.db import models

# Create your models here.

class Trabajos(models.Model):
    nombre = models.CharField(max_length=50)
    tiempo = models.CharField(max_length=50,  null=True)
    precio = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre

class Trabajadores(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField()
    tra = models.ForeignKey(Trabajos, on_delete=models.PROTECT ,  null=True)
    rut = models.CharField(max_length=12)
    correo = models.EmailField(max_length=254)
    fecha_inicio = models.DateField()
    imagen = models.ImageField(upload_to="trabajadores", null=True)
    
    
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nom_trabajador = models.ForeignKey(Trabajadores, on_delete=models.PROTECT)
    descripcion = models.TextField()
    trabajos = models.ForeignKey(Trabajos, on_delete=models.PROTECT)
    foto = models.ImageField(upload_to="productos", null=True)
        
    def __str__(self):
        return self.nom_trabajador.nombre
    
    
opciones_consultas = [
    [0, "consulta"  ],
    [1, "reclamo"  ],  
    [2, "sugerencia"  ],  
    [3, "felicitaciones"  ]      
]    
    
class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consultas)
    mensaje = models.TextField()
    avisos = models.BooleanField()
    
    def __str__(self):
        return self.nombre
    
    

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'app/img/about/incon.png' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
            <div class="container-fluid">
              <img src="{% static 'app/img/logos prueba/icon.png' %}" alt="Logo" width="60" height="40" class="d-inline-block align-text-top">
              <a href="{% url 'home' %}" class="navbar-brand">RayoMkuin</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item"> 
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Inicio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'galeria2' %}">Trabajos</a>
                  </li>
                  <li>
                    <a class="nav-link" href="{% url 'galeria' %}">Trabajadores</a>
                  </li>

                  {% if perms.app.add_producto %}
                  <li><a class="nav-link" href="{% url 'agregar_producto' %}">Atribuir Trabajo</a></li>
                  {% endif %}
                  {% if perms.app.add_trabajadores %}
                  <li><a class="nav-link" href="{% url 'agregar_trabajador' %}">Agregar Trabajador</a></li>
                  {% endif %}
                  {% if perms.app.view_producto %}
                  <li><a class="nav-link" href="{% url 'listar_productos' %}">Lista Trabajador</a></li>
                  {% endif %}

                  {% if user.is_authenticated %}
                  <li class="nav-item" id="usuario">
                    <a class="nav-link active" aria-current="page" href="{% url 'usuario' %}"> Hola, {{ user.username}}</a>
                  </li>
                  {% endif %}

                </ul>
                  <div class="LOGIN">
                  <ul>
                  {% if user.is_authenticated %}
                    <li>
                      <a class="boton1" href="{% url 'logout' %}" >Cerrar Sesion</a>
                    </li>
                    {% else %}
                    <li>
                      <a class="boton1" href="{% url 'login' %}" >Iniciar Sesion</a>
                      <a class="boton1" href="{% url 'registro' %}" >Registrate</a>
                    </li>
                    {% endif %}
                  </ul>
                      

                  </div>
              </div>
            </div>
          </nav>
    </header>

    <div class="mb-5 mt-5 pt-5 pb-5" id="contenido">
        {% block contenido %}

        {% endblock %}
    </div>

    <footer>
      <div class="bg-dark">
        <div class="text-white text-center">
            <h2> Trabajo Taller Mecanico </h2>
        </div>
        <br>
        <div class="text-center">
          <img src="{% static 'app/img/logos prueba/Logo_DuocUC.svg.png' %}" style="height: 100px; width: 1x00px">
        </div>
      </div> 
      
  </footer> 

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'app/java/app.js' %}"></script> 
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %} 
      {% for m in messages %}
        <script>
          Swal.fire({
            "title": "Felicitaciones",
            "text": "{{m}}",
            "icon": "success"
          })
        </script>
          
      {% endfor%}
    {% endif %}
</body>
</html>

app/templates/app/carrito2.html
{% block contenido %}
<div class="alert alert-primary">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="row" colspan="3" class="text-center">Carrito</th>
            </tr>
            <tr>
                <th scope="col">NOMBRE</th>
                <th scope="col">PRECIO</th>
                <th scope="col">CANTIDAD</th>
            </tr>
        </thead>
        <tbody>
            {% if request.session.carrito.items %}
            {% for key, value in request.session.carrito.items %}
                <tr>
                    <td>{{value.nombre}}</td>
                    <td>{{value.precio}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>{{value.precio}}
                        <a href="{% url 'Add' value.producto_id %}" class="badge btn btn-dark badge-dark">+</a>
                        <a href="{% url 'Sub' value.producto_id %}" class="badge btn btn-dark badge-dark">-</a>
                    </td>
                </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">Sin Productos</div>

                </td>
            </tr>
            {% endif %}
            <tr>
                <th scope="row">Total</th>
                <td colspan="2">${{total_carrito}}</td>
            </tr>
        </tbody>
    </table>
    <hr>
    <div class="row text-center">
        <div class="col-6"><a href="{% url 'CLS' %}" class="btn btn-danger">Limpiar</a></div>
        <div class="col-6"><a href="{% url 'webpay' %}" class="btn btn-success">Ir a Pagar</a></div>

    </div>

</div>

{% endblock %}

app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block contenido %}

<div class="row">

    <div class="col-12 col-md-6 offset-md-3 text-white">
        <div class="card bg-dark">
            <div class="card-body text-white">
                <h2>Contactanos!</h2>

                <form action="" class="text-white" method="post">
                    {% csrf_token %}
        
                    {{ form }}
        
                    <br>
                    x<div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <button type="submit" id="btnEnviar" class="button">Enviar</button>   
                    </div>
                    
                </form>
        
                {{ mensaje }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/galeria.html
{%extends 'app/base.html' %}

{%load static%}

{%block contenido %}

<div class="med mt-5 pt-5">
    <div class="row">
        <div class="col-md-12">

            <div class="section-header text-center text-white pb-5">
              <h2> Aqui podras ver nuestros trabajadores :</h2>
            </div>
          </div>
    </div>
</div>


{% load humanize %}

<div class="container">
    <div class="row">
  
      {% for p in trabajadores %}
      <div class="col-12 col-md-6 col-lg-4 mt-3">
        <div class="card text-center bg-dark d-flex align-items-center">
          {% if p.imagen %}
          <img src="{{ p.imagen.url }}" style="height: 200px; width: 200px" alt="...">
          {% endif %}
          <div class="card-body text-white">
            <p class="card-title">Nombre: {{ p.nombre }}</p>
            <p class="card-title">Rut: {{ p.rut }}<br></p>
            <p class="card-text">Trabajando desde {{ p.fecha_inicio }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
  
    </div>
  </div>

{%endblock %}

app/templates/app/galeria2.html
{%extends 'app/base.html' %}

{%load static%}

{%block contenido %}


<div class="container">
  <div class="row">
      <div class="col-12 align-self-center"><h1 class="display text-white">Servicios</h1></div>
  </div>
  <div class="row">
      <div class="col-8">
          <div class="row" style="padding: 10px 0 ;">
              <div class="col-12 text-white">
                  Lista de servicios:
                  <div class="row">
                      
                      
                      {% load humanize %}
                      <br>
                      {% for p in productos %}
                      <div class="col-6 pt-4">
                          <div class="card text-center bg-dark text-white d-flex align-items-center">
                             <div class="card-body">
                                {% if p.foto %}
                                <img src="{{ p.foto.url }}" style="height: 100px; width: 100px" alt="...">
                                {% endif %}
                                <p class="card-title">Trabajo disponible por: {{ p.nom_trabajador }}</p>
                                <p class="card-text">
                                  Especialista en {{ p.trabajos }}<br>
                                  Valor de: {{ p.trabajos.precio|intcomma }}
                                </p>
                                <a href="{% url 'Add' p.id %}" class="btn btn-primary">Agregar al Carrito</a>
                             </div> 
                          </div>
                      </div>
                      {% endfor %}
                  </div>
              </div>
          </div>
      </div>
      <div class="col-4">
          {% include "app/carrito2.html" %}
      </div>
  </div>
</div>
{% load humanize %}



{%endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block contenido %}
<span name="ini" id="ini"></span>

<div class="container mt-5 pt-3 mb-3">
  <div id="carouselExampleIndicators" class="carousel slide">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <a href="{% url 'galeria' %}">
          <img src="{% static 'app/img/carru/c1.jpg' %}" class="d-block w-100" alt="...">
        </a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Alineamiento de Neumaticos</h5>
          <a class="btn btn-primary" href="{% url 'galeria2' %}">Mas informacion</a>
        </div>
      </div>
      <div class="carousel-item">
        <a href="proye2.html">
          <img src="{% static 'app/img/carru/c2.jpg' %}" class="d-block w-100" alt="...">
        </a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Cambio de aceite</h5>
          <a class="btn btn-primary" href="{% url 'galeria2' %}">Mas informacion</a>
        </div>
      </div>
      <div class="carousel-item">
        <a href="{% url 'galeria' %}">
          <img src="{% static 'app/img/carru/c3.jpg' %}" class="d-block w-100" alt="...">
        </a>
        <div class="carousel-caption d-none d-md-block">
          <h5>Cambio de bujias</h5>
          <a class="btn btn-primary" href="{% url 'galeria2' %}">Mas informacion</a>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<span name="awe" id="awe"></span>
<div class="container mt-5 pt-5 card-section">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-6 mt-3">
      <div class="card text-center bg-dark">
        <div class="card-img-container">
          <img src="{% static 'app/img/otros servicios/auto.jpg' %}" class="card-img" alt="...">
        </div>
        <div class="card-body text-white">
          <h5 class="card-title">Quieres vender tu auto?</h5>
          <p class="card-text">Trae tu vehículo y nosotros lo evaluaremos y nos encargaremos de dejarlo a punto para su venta que puede ser realizada con nuestra página afiliada.</p>
          <a href="#" class="btn btn-primary">Ir al sitio</a>
        </div>
      </div>
    </div>

    <div class="col-12 col-md-6 col-lg-6 mt-3">
      <div class="card text-center bg-dark">
        <div class="card-img-container">
          <img src="{% static 'app/img/otros servicios/auto1.jpg' %}" class="card-img" alt="...">
        </div>
        <div class="card-body text-white">
          <h5 class="card-title">La suciedad no es lo de menos</h5>
          <p class="card-text">Así como queremos mantener tu auto en perfecto estado, también queremos cuidar su apariencia. Por eso, contamos con un servicio de lavado de autos.</p>
          <a href="#" class="btn btn-primary">Ir al sitio</a>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}

app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}